image: ghcr.io/juliandavis/c-build:1.0.0

aliases:
  uurl:
    script:
      - scons -j$(nproc)
      - valgrind -q build/bin/x86_64-linux/test/uurl/test_parse_response.runner
      - valgrind -q build/bin/x86_64-linux/test/uurl/test_parse_request.runner

  cosmo:
    script:
      - scons -f cosmo.SConstruct -j$(nproc)
      - valgrind -q build/bin/x86_64-linux/test/cosmo/test_parse_response.runner
      - valgrind -q build/bin/x86_64-linux/test/cosmo/test_parse_request.runner

  clean: if [ -d build ]; then rm -r build; fi;
