Import('env')

libuurl = env.StaticLibrary(
    target='uurl',
    source=[
        'http_header.c',
        'http_parse.c',
        'http_token.c',
        'uurl.c',
        'net.c',
        'io.c',
    ],
)

libuurl_test = env.Program(
    target='libuurl_test',
    source=['test.c'],
    LIBS=[libuurl],
)

Return('libuurl', 'libuurl_test')
